name: Build Kile on macOS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Homebrew dependencies
      run: |
        brew update
        brew install cmake qt5 kde-mac/kde/kf5-kconfig kde-mac/kde/kf5-kcoreaddons \
                     kde-mac/kde/kf5-ki18n kde-mac/kde/kf5-kwindowsystem kde-mac/kde/kf5-kxmlgui

    - name: Clone Kile source code
      run: |
        git clone https://invent.kde.org/office/kile.git
        cd kile

    - name: Build Kile
      run: |
        cd kile
        mkdir build && cd build
        cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix)/opt/qt@5
        make -j$(sysctl -n hw.ncpu)
        ls -l
