name: Build Kile for macOS  
  
on:  
  push:  
    branches:  
      - main  
  pull_request:  
    branches:  
      - main  
  workflow_dispatch:  
  
jobs:  
  build-macos:  
    runs-on: macos-latest  
      
    steps:  
    - name: Clone KDE/kile repository  
      uses: actions/checkout@v4  
      with:  
        repository: KDE/kile  
        ref: main  
          
    - name: Install basic dependencies  
      run: |  
        brew update  
        brew install cmake ninja qt6 extra-cmake-modules  
          
    - name: Set up environment  
      run: |  
        echo "CMAKE_PREFIX_PATH=$(brew --prefix qt6):$(brew --prefix extra-cmake-modules)" >> $GITHUB_ENV  
        echo "PKG_CONFIG_PATH=$(brew --prefix)/lib/pkgconfig" >> $GITHUB_ENV  
          
    - name: Create build directory  
      run: mkdir build  
        
    - name: Configure with CMake  
      working-directory: build  
      run: |  
        cmake .. \  
          -DCMAKE_BUILD_TYPE=Release \  
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install \  
          -DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH" \  
          -DAPPLE_SUPPRESS_X11_WARNING=ON \  
          -GNinja  
            
    - name: Check CMake configuration  
      working-directory: build  
      run: |  
        if [ ! -f build.ninja ]; then  
          echo "CMake configuration failed - no build.ninja generated"  
          cat CMakeFiles/CMakeError.log || echo "No CMakeError.log found"  
          exit 1  
        fi  
        echo "CMake configuration successful"  
          
    - name: Build Kile  
      working-directory: build  
      run: ninja -j$(sysctl -n hw.ncpu)  
        
    - name: Install Kile  
      working-directory: build  
      run: ninja install  
        
    - name: Create macOS app bundle  
      run: |  
        mkdir -p Kile.app/Contents/MacOS  
        mkdir -p Kile.app/Contents/Resources  
        cp -r install/* Kile.app/Contents/  
          
        # Create Info.plist based on CMake macOS bundle configuration  
        cat > Kile.app/Contents/Info.plist << EOF  
        <?xml version="1.0" encoding="UTF-8"?>  
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">  
        <plist version="1.0">  
        <dict>  
            <key>CFBundleExecutable</key>  
            <string>Kile</string>  
            <key>CFBundleIdentifier</key>  
            <string>org.kde.kile</string>  
            <key>CFBundleName</key>  
            <string>Kile</string>  
            <key>CFBundleDisplayName</key>  
            <string>Kile</string>  
            <key>CFBundleInfoDictionaryVersion</key>  
            <string>6.0</string>  
            <key>CFBundlePackageType</key>  
            <string>APPL</string>  
        </dict>  
        </plist>  
        EOF  
          
    - name: Bundle dependencies with macdeployqt  
      run: |  
        $(brew --prefix qt6)/bin/macdeployqt Kile.app -verbose=2  
          
    - name: Create DMG  
      run: |  
        hdiutil create -volname "Kile" -srcfolder Kile.app -ov -format UDZO Kile-macOS.dmg  
          
    - name: Upload build artifacts  
      uses: actions/upload-artifact@v4  
      with:  
        name: kile-macos-build  
        path: |  
          Kile-macOS.dmg  
          Kile.app
