name: Build Kile for macOS with Craft  
  
on:  
  push:  
    branches:  
      - main  
  pull_request:  
    branches:  
      - main  
  workflow_dispatch:  
  
jobs:  
  build-macos:  
    runs-on: macos-latest  
      
    steps:  
    - name: Clone KDE/kile repository  
      uses: actions/checkout@v4  
      with:  
        repository: KDE/kile  
        ref: master  
          
    - name: Install Python and basic tools  
      run: |  
        brew install python3 git  
          
    - name: Setup Craft  
      run: |  
        git clone -b master https://invent.kde.org/packaging/craft.git  
        cd craft/setup  
        python3 CraftBootstrap.py --prefix ${{ github.workspace }}/craft-root  
          
    - name: Initialize Craft environment  
      run: |  
        source ${{ github.workspace }}/craft-root/craft/bin/activate  
        craft --add-blueprint-repository https://invent.kde.org/packaging/craft-blueprints-kde.git  
          
    - name: Build Kile with Craft  
      run: |  
        source ${{ github.workspace }}/craft-root/craft/bin/activate  
        craft kile  
          
    - name: Package Kile  
      run: |  
        source ${{ github.workspace }}/craft-root/craft/bin/activate  
        craft --package kile  
          
    - name: Upload build artifacts  
      uses: actions/upload-artifact@v4  
      with:  
        name: kile-macos-craft-build  
        path: ${{ github.workspace }}/craft-root/tmp/
